backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

local_backend: true

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "contentType", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - label: 'Category'
        name: 'category'
        widget: 'relation'
        collection: 'postCategory'
        searchFields: ['title']
        valueField: 'title'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        required: false
      - {label: "URL Slug", name: "slug", widget: "string"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: postCategory
    label: Post Category
    editor:
      preview: false
    folder: content/postCategory
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Type", name: "contentType", widget: "hidden", default: "postCategory"}
      - { label: ID, name: id, widget: number }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - {
          label: Featured Image,
          name: featuredImage,
          widget: image,
          required: false,
        }
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }
  - name: postTags
    label: Post Tags
    editor:
      preview: false
    folder: content/postTags
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Type", name: "contentType", widget: "hidden", default: "postTags"}
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - label: 'Category'
        name: 'category'
        widget: 'relation'
        collection: 'postCategory'
        searchFields: ['title']
        valueField: 'title'
      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }